### ISSUE TITLE
Editing Obstacle and Item Properties

### ISSUE THREAD

**Issue by knot126** [Skinnerpuma737/Smash-Hit-Editor#2]
We will need to decide how the interface for editing obstacle properties should look. This also goes for decals, power-ups, and (possibly) water.

I think it's important that we keep the interface simple and easy to use (that is: not blender tools), which will be an advantage for this editor. (Besides the fact that it is actually designed for creating Smash Hit levels.)

**Comment by Skinnerpuma737** [comment]
Ye i have some idea on what it should look like i will make a sketch and put it on the google docs page
